language: swift

branches:
  only:
    - master

xcode_project: Permission.xcodeproj
xcode_scheme: PermissionTests
osx_image: xcode11.2

script:
  - xcodebuild test -project Permission.xcodeproj -scheme PermissionTests -destination "platform=iOS Simulator,name=iPhone 11"
